driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  associate_public_ip: false
  interface: private
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>

provisioner:
  name: chef_zero
  data_bags_path: "data_bags"
  roles_path: "roles"
  environments_path: "environments"
  require_chef_omnibus: true

transport:
  ssh_key: <%= ENV['SSH_KEY_PATH'] %><%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: ubuntu-12.04
    driver:
      image_id: <%= ENV['AWS_UBUNTU12_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_UBUNTU12_USERNAME'] %>
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV['AWS_UBUNTU14_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_UBUNTU14_USERNAME'] %>
    run_list:
      - recipe[apt::default]
  - name: centos-6.7
    driver:
      image_id: <%= ENV['AWS_CENTOS6_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS6_USERNAME'] %>
  - name: centos-7.1
    driver:
      image_id: <%= ENV['AWS_CENTOS7_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS7_USERNAME'] %>

suites:
- name: default
  run_list:
    - recipe[sysctl_test]
    - recipe[sysctl_test::tcp_wmem]
    - recipe[sysctl::ohai_plugin]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29
- name: lwrps
  run_list:
    - recipe[sysctl_test]
    - recipe[sysctl_test::tcp_wmem]
- name: attributes
  run_list:
    - recipe[sysctl::apply]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29

